name: Release

on:
  workflow_call:
    inputs:
      build-artifact-name:
        description: "The name of the build artifact."
        type: string
        required: false
        default: "build"
      build-artifact-path:
        description: "The path of the build artifact."
        type: string
        required: false
        default: ".build"
      build-zip-path:
        description: "The path of the build ZIP."
        type: string
        required: false
        default: "../build.zip"
      deploy-artifact-name:
        description: "The name of the deploy artifact."
        type: string
        required: false
        default: "deploy"
      deploy-artifact-path:
        description: "The path of the deploy artifact."
        type: string
        required: false
        default: ".deploy"
      deploy-zip-path:
        description: "The path of the deploy ZIP."
        type: string
        required: false
        default: "../deploy.zip"
    secrets:
      CFL_BOT_GH_TOKEN:
        description: "The CFL-bot's GitHub token. Used to release."
        required: true

jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    # Release if:
    #  - the repo's owner is Ocado Tech.
    #  - a change is made to the default branch.
    if: |
      github.repository_owner_id == 2088731 &&
      github.ref_name == github.event.repository.default_branch
    env:
      NODE_VERSION: 22
    steps:
      - name: ğŸ›« Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CFL_BOT_GH_TOKEN }}
          fetch-depth: 0

      - name: ğŸ“¥ Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.build-artifact-path }}

      - name: ğŸ“¥ Download Deploy Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.deploy-artifact-name }}
          path: ${{ inputs.deploy-artifact-path }}

      - name: ğŸŒ Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ›  Install Dependencies
        run: |
          npm install --global npm
          npm install --global \
            semantic-release@^20.1.1 \
            @semantic-release/git@^10.0.1 \
            @semantic-release/changelog@^6.0.2

      - name: ğŸ“ Zip Build Files
        working-directory: ${{ inputs.build-artifact-path }}
        run: zip --quiet --recurse-paths ${{ inputs.build-zip-path }} .

      - name: ğŸ“ Zip Deploy Files
        working-directory: ${{ inputs.deploy-artifact-path }}
        run: zip --quiet --recurse-paths ${{ inputs.deploy-zip-path }} .

      - name: ğŸš€ Publish Semantic Release
        env:
          GH_TOKEN: ${{ secrets.CFL_BOT_GH_TOKEN }}
          GIT_AUTHOR_NAME: cfl-bot
          GIT_AUTHOR_EMAIL: codeforlife-bot@ocado.com
          GIT_COMMITTER_NAME: cfl-bot
          GIT_COMMITTER_EMAIL: codeforlife-bot@ocado.com
        run: npx semantic-release
